fix: Convert to binding cells to resolve undefined node label error.
File "/__w/zmk-config/zmk-config/zmk/modules/zephyr/zephyr/scripts/dts/python-devicetree/src/devicetree/dtlib.py", line 2089, in _err raise DTError(msg)
devicetree.dtlib.DTError: expected property 'bindings' on /behaviors/sticky_ctrl_long in /__w/zmk-config/zmk-config/zmk/modules/zephyr/zephyr/misc/empty_file.c to be assigned with 'bindings = < &foo &bar ... >;', not 'bindings = < &kp 0x700e0 >;'